--- #YAML:1.0
name: Config-OpenSSH-Authkey
abstract: interface to OpenSSH authorized_keys data
version: 0.65
author:
  - Jeremy Mates <jmates@sial.org>
license: artistic
distribution_type: module
requires:
  perl: 5.006
  Carp: 0
recommends:
  File::AtomicWrite: 0
build_requires:
  Test::More: 0.72
resources:
  license: http://dev.perl.org/licenses/artistic.html
  repository: http://github.com/thrig/Config-OpenSSH-Authkey
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Config-OpenSSH-Authkey
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: hand
